milista=["María", "Diego", 5,"Luis","Marta", "Carlos","Raquel","Jose","Estrella","Nicolás"] * 3
print (milista[:])
print(milista[3])
print(milista[-3])
print(milista[3:6])
print(milista[:3])
print (milista[5:])
milista. append("Sandra")
print (milista[:])
milista.insert(4,"Laura")
milista.insert(5,"Pablo")
print (milista[:])
milista.extend([0.5,"Vanesa",15,"Dolores","Moises","Raquel","Paco"])
print (milista[:])
print(milista.index(0.5))
print(milista.index("Raquel"))
print("Pepe"in milista)
milista.remove("Dolores")
milista.pop()

